// servo_task.c

#include "servo_task.h"
#include "cmsis_os.h"
#include "logger/logger.h"
#include "shared_state.h"
#include "stm32f4xx_hal.h"

// These are generated by CubeMX — declared in main.c
extern TIM_HandleTypeDef htim2;
extern ADC_HandleTypeDef hadc1;

static TaskHandle_t servoTaskHandle = NULL;

#define THRESHOLD_LOW  180
#define THRESHOLD_HIGH 200

static uint8_t servo_active = 0;

volatile uint32_t debug_adc   = 0;
volatile uint32_t debug_pulse = 0;

// Map ADC 12-bit (0–4095) to PWM pulse (1000–2000 µs)
static uint32_t adc_to_pulse(uint32_t adc_val)
{
    return 1000 + (adc_val * 1000) / 4095;
}

// Task function
static void ServoTask(void *argument)
{
    HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);
    servo_active = 1;
    for (;;)
    {
        HAL_ADC_Start(&hadc1);

        if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
        {
            uint32_t adc_val = HAL_ADC_GetValue(&hadc1);
            // log_info("ADC value: %lu", adc_val);

            if (servo_active)
            {
                uint32_t pulse = adc_to_pulse(adc_val);
                debug_adc      = adc_val;
                debug_pulse    = pulse;
                __HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, pulse);
            }

            // Publish ADC reading for the USB HID report.
            // Map 12-bit ADC (0–4095) → signed byte (-127 to +127).
            int8_t axis = (int8_t) ((int32_t) adc_val * 254 / 4095 - 127);
            if (xSemaphoreTake(joystick_mutex, pdMS_TO_TICKS(5)) == pdTRUE)
            {
                joystick_state.x = axis;
                xSemaphoreGive(joystick_mutex);
            }
        }

        vTaskDelay(pdMS_TO_TICKS(20));
    }
}

// Function to create the task
void ServoTask_Create(void)
{
    xTaskCreate(
        ServoTask,         // Task function
        "ServoTask",       // Name (for debug)
        128,               // Stack size (in words)
        NULL,              // Parameters
        2,                 // Priority
        &servoTaskHandle); // Handle
}