// servo_task.c

#include "servo_task.h"
#include "cmsis_os.h"
#include "stm32f4xx_hal.h"

// These are generated by CubeMX — declared in main.c
extern TIM_HandleTypeDef htim2;
extern ADC_HandleTypeDef hadc1;

static TaskHandle_t servoTaskHandle = NULL;

#define THRESHOLD_LOW  180
#define THRESHOLD_HIGH 200

static uint8_t servo_active = 0;

volatile uint32_t debug_adc   = 0;
volatile uint32_t debug_pulse = 0;

// Map ADC 12-bit (0–4095) to PWM pulse (1000–2000 µs)
static uint32_t adc_to_pulse(uint32_t adc_val)
{
    return 1000 + (adc_val * 1000) / 4095;
}

// Task function
static void ServoTask(void *argument)
{
    HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);
    servo_active = 1;
    for (;;)
    {
        HAL_ADC_Start(&hadc1);

        if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
        {
            uint32_t adc_val = HAL_ADC_GetValue(&hadc1);

            // ~0.001V on a 3.3V / 12-bit ADC = roughly ADC value 1-2
            // We use a small threshold (< 10) to catch near-zero reliably

            if (adc_val < THRESHOLD_LOW)
            {
                servo_active = 0;
            }
            else if (adc_val > THRESHOLD_HIGH)
            {
                servo_active = 1;
            }

            if (servo_active)
            {
                uint32_t pulse = adc_to_pulse(adc_val);
                debug_adc      = adc_val;
                debug_pulse    = pulse;
                __HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, pulse);
            }
        }

        vTaskDelay(pdMS_TO_TICKS(20));
    }
}

// Function to create the task
void ServoTask_Create(void)
{
    xTaskCreate(
        ServoTask,         // Task function
        "ServoTask",       // Name (for debug)
        128,               // Stack size (in words)
        NULL,              // Parameters
        2,                 // Priority
        &servoTaskHandle); // Handle
}